import "./globals.css";
import { Header } from "../Components/Header";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>     
          <Header logo="Logo" />
          {children}       
      </body>
    </html>
  );
}
