import { Header } from "@/Components/Header";
import "./globals.css";
import ContextProvider from "@/Helper/Context"; // ✅ assuming default export

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressContentEditableWarning>
        <Header logo={"Logo"} />
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
